server:
  port: 8081
  servlet:
    context-path: /intelligent
spring:
  application:
    name: intelligent
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.241.95:3306/intelligent_person?characterEncoding=UTF-8
    username: root
    password: 3264290
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    connect-timeout: 30000
mybatis:
  type-aliases-package: com.user.entity,com.monitor.entity,com.custody.entity,com.lost.entity,com.service.entity,com.query.entity,com.social.entity
  mapper-locations: classpath:com/user/mapper/xml/*.xml,classpath:com/monitor/mapper/xml/*.xml,classpath:com/custody/mapper/xml/*.xml,classpath:com/lost/mapper/xml/*.xml,classpath:com/service/mapper/xml/*.xml,classpath:com/query/mapper/xml/*.xml,classpath:com/social/mapper/xml/*.xml
logging:
  level:
    com.user.mapper: debug
    com.monitor.mapper: debug
    com.custody.mapper: debug
    com.lost.mapper: debug
    com.service.mapper: debug
    com.query.mapper: debug
    com.social.mapper: debug
intelligent :
  minio:
    minio_url: http://127.0.0.1:9000/
    minio_accessKey: minioadmin
    minio_secretKey: minioadmin
